site_name: Yurii Rashkovskii
site_description: Writings on software development and work practices, entrepreneurship, tech in general.
site_url: https://yrashk.com

watch:
  - .

theme:
  name: material
  font:
    text: Poppins
  custom_dir: overrides
  features:
    - navigation.tabs
    - content.tooltips
    - announce.dismiss
    - navigation.top
    - navigation.instant
  logo: yrashk.jpeg
  favicon: favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - blog:
      archive: false
  - search
  - include-markdown
  - privacy:
      external_assets_exclude:
        - giscus.app/*
  - social:
      cards_color:
        fill: "#D63964"
  - meta
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

nav:
  - Home: index.md
  - Open Source: opensource/index.md
  - Blog: blog/index.md
